name: Update contributors image

on:
  schedule:
    - cron: "0 0 * * 0"  # every Sunday at midnight
  workflow_dispatch:     # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow committing changes
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pillow requests

      - name: Generate contributors SVG
        env:
          GITHUB_ORG: EarthSciML
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/generate_contributors.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add contributors.svg
          git commit -m "Update contributors SVG" || echo "No changes to commit"
          git push
